authuser/urls.py
from django.urls import path, include

from .views import user_login, user_register, user_logout

urlpatterns = [
    path('login', user_login, name = 'login'),
    path('register', user_register, name = 'register'),
    path('logout', user_logout, name = 'logout')
]

app_name = 'authuser'

setoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls', namespace = 'authuser')),
    path('', include('toko.urls', namespace = 'toko')),
    path('contactus/', include('contactus.urls', namespace = 'contactus')),
    path('donasi/', include('donasi.urls', namespace = 'donasi')),
    path('detail/', include('detail.urls', namespace = 'detail')),
    path('checkout/', include('checkout.urls', namespace = 'checkout')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path

from .views import index, toko, tambah, search_keyword, search_keyword_all, search_category, edit, hapus, toko_user, clean_notif, get_notif, cart, add_to_cart

urlpatterns = [
    path('toko/', toko, name = 'toko'),
    path('toko/tambah/', tambah, name = 'tambah'),
    path('toko/search/keyword/<str:keyword>/', search_keyword, name='search_keyword'),
    path('toko/search/keyword/', search_keyword_all, name='search_keyword_all'),
    path('toko/search/category/<str:category>/', search_category, name='search_category'),
    path('toko/edit/<int:id_barang>/', edit, name='edit'),
    path('toko/hapus/<int:id_barang>/', hapus, name='hapus'),
    path('toko/user/<int:id_user>/', toko_user, name='toko_user'),
    path('toko/user/cart/', cart, name='cart'),
    path('toko/api/notif/clean/', clean_notif, name='clean_notif'),
    path('toko/api/notif/get/', get_notif, name='get_notif'),
    path('toko/api/cart/add/', add_to_cart, name='add_to_cart'),
    path('', index, name = 'index'),
]

app_name = 'toko'

authuser/models.py
from django.db import models

# Create your models here.

authuser/forms.py
from django import forms

class AuthForm(forms.Form):
    nama = forms.CharField(
        max_length = 300,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
                'placeholder': 'Masukkan username'
            }
        )
    )
    
    password = forms.CharField(
        max_length = 20,
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
                'placeholder': 'Masukkan password'
            }
        )
    )

authuser/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User 

from .forms import AuthForm

# Create your views here.
def user_login(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('toko:index'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = authenticate(
            username = request.POST['nama'],
            password = request.POST['password'],
        )

        if (account == None):
            context['isError'] = True
            context['Error'] = 'Autentikasi gagal'
            context['Form'] = AuthForm()
            return render(request, 'authuser/login.html', context)
        else:
            login(request, account)
            return redirect(resolve_url('toko:index'))



    return render(request, 'authuser/login.html', context)

def user_register(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('toko:index'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        acount = None
        try:
            account = User.objects.get(username = request.POST['nama'])
        except:
            account = None
        if (account == None):
            new_account = User.objects.create_user(request.POST['nama'], '', request.POST['password'])
            new_account.save()
            login(request, new_account)
            return redirect(resolve_url('toko:index'))
        else:
            context['isError'] = True
            context['Error'] = 'Sudah ada akun dengan username ' + request.POST['nama']
            context['Form'] = AuthForm()
            return render(request, 'authuser/register.html', context)


    return render(request, 'authuser/register.html', context)

def user_logout(request):
    logout(request)
    return redirect(resolve_url('authuser:login'))

authuser/templates/authuser/login.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Masuk
{% endblock title %}

{% block content %}
<style>
    section{
        margin-bottom: 50px;
    }

    button .btn.btn-login {
        background: ;
    }
</style>
<section id="register">
    <div class="container" style="max-width:60%">
        <h1 class="text-center">Masuk</h1>
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-login btn-block" style="background: #F63; color: white">Login</button>
                </form>
                <p>Belum punya akun? <a href="{% url 'authuser:register' %}#register" style="color: #F63">Register</a></p>
            </div>
        </div>
    </div>

</section>
{% endblock content %}

authuser/templates/authuser/register.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Buat Akun
{% endblock title %}

{% block content %}
<style>
    section{
        margin-bottom: 50px;
    }
</style>
<section id="register">
    <div class="container" style="max-width:60%">
        <h1 class="text-center">Buat Akun</h1>
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-block" style="background: #F63; color: white">Register</button>
                </form>
                <p>Sudah punya akun? <a href="{% url 'authuser:login' %}#login" style="color: #F63">Login</a></p>
            </div>
        </div>
    </div>

</section>
{% endblock content %}