donasi/urls.py
from django.urls import path
from . import views

app_name = 'donasi'

urlpatterns = [
    path('', views.donasi, name = 'donasi'),
    path('terimakasih/', views.terimakasih, name = 'terimakasih'),
    path('totaldonasi/', views.totaldonasi, name = 'totaldonasi'),
    path('api/', views.donasi_api2, name = 'api2'),
    path('api/<str:nama>', views.donasi_api, name = 'api'),
]

setoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls', namespace = 'authuser')),
    path('', include('toko.urls', namespace = 'toko')),
    path('contactus/', include('contactus.urls', namespace = 'contactus')),
    path('donasi/', include('donasi.urls', namespace = 'donasi')),
    path('detail/', include('detail.urls', namespace = 'detail')),
    path('checkout/', include('checkout.urls', namespace = 'checkout')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path

from .views import index, toko, tambah, search_keyword, search_keyword_all, search_category, edit, hapus, toko_user, clean_notif, get_notif, cart, add_to_cart

urlpatterns = [
    path('toko/', toko, name = 'toko'),
    path('toko/tambah/', tambah, name = 'tambah'),
    path('toko/search/keyword/<str:keyword>/', search_keyword, name='search_keyword'),
    path('toko/search/keyword/', search_keyword_all, name='search_keyword_all'),
    path('toko/search/category/<str:category>/', search_category, name='search_category'),
    path('toko/edit/<int:id_barang>/', edit, name='edit'),
    path('toko/hapus/<int:id_barang>/', hapus, name='hapus'),
    path('toko/user/<int:id_user>/', toko_user, name='toko_user'),
    path('toko/user/cart/', cart, name='cart'),
    path('toko/api/notif/clean/', clean_notif, name='clean_notif'),
    path('toko/api/notif/get/', get_notif, name='get_notif'),
    path('toko/api/cart/add/', add_to_cart, name='add_to_cart'),
    path('', index, name = 'index'),
]

app_name = 'toko'

donasi/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError 

# Create your models here.
def validate_donasi(value):
    if (value >= 1000):
        return value
    else :
        raise ValidationError("Jumlah donasi harus lebih besar atau sama dengan 1000")

class Donasi(models.Model):
    pengirim = models.CharField(max_length = 100, default = "setokoadmin")
    tokotujuan = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    jumlahdonasi = models.IntegerField('Jumlah Donasi ', validators=[validate_donasi])

    def __str__(self):
        return '{} {}'.format(self.tokotujuan, self.jumlahdonasi)

class Donatur(models.Model):
    namaDonatur = models.CharField(max_length=100)
    jumlahDonasi = models.IntegerField()

    def __str__(self):
        return '{} {}'.format(self.namaDonatur, self.jumlahDonasi)    

donasi/forms.py
from django.forms import ModelForm
from django import forms
from .models import Donasi
# from django.contrib.auth.models import User

# tokos = [(i,i) for i in User.objects.all()]

class DonasiForm(ModelForm):
    class Meta:
        model = Donasi
        fields = '__all__'
        widgets = {
            # 'tokotujuan': forms.Select(choices=tokos, attrs={
            #     'placeholder': "Masukkan toko tujuan donasi",
            # }),
            'jumlahdonasi' : forms.NumberInput(attrs={
                'placeholder' : "Masukkan jumlah donasi yang diinginkan",
                'class' : "form-control"
            })
        }
        error_messages = {
            'tokotujuan': {
                'required': "Tujuan tidak boleh kosong",
            },
            'jumlahdonasi': {
                'required': "Jumlah donasi tidak boleh kosong",
                'invalid': "Masukkan jumlah yang valid"
            }
        }
        help_texts ={
            'jumlahdonasi' : 'Jumlah donasi minimal adalah 1000',
        }

donasi/views.py
from django.shortcuts import render,redirect, resolve_url
from .forms import DonasiForm
from django.urls import reverse
from django.contrib.auth.models import User 
from django.contrib.auth import get_user_model
from toko.models import Notifikasi
from django.core import serializers
from .models import Donasi, Donatur
from django.contrib import messages
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def donasi(request):
    User = get_user_model()
    users = User.objects.all()
    usernow = request.user.username
    donasierror = False
    if (request.user.is_anonymous):
        return redirect('authuser:login')

    formDonasi= DonasiForm()
    if request.method == 'POST':
        form = DonasiForm(request.POST or None)
        namaDonatur = request.POST.get('pengirim', 'Hamba Allah')
        jumlahDonasi = request.POST.get('jumlahdonasi')

        try:
            # print("sukgasih")
            donaturObj = Donatur.objects.get(namaDonatur = namaDonatur)
            donaturObj.jumlahDonasi += int(jumlahDonasi)
            # print("hah")
            donaturObj.save()
            # print("Masuk1")
        except ObjectDoesNotExist:
            newDonatur = Donatur(namaDonatur=namaDonatur, jumlahDonasi=jumlahDonasi)
            newDonatur.save()
            # print("Masuk2")

        if form.is_valid():
            form.save()
            pengirim = request.POST['pengirim']
            # print(pengirim)
            toko_tujuan = User.objects.get(id = request.POST['tokotujuan'])
            jumlah_donasi = request.POST['jumlahdonasi']
            isi_notifikasi = 'Pengguna ' + request.user.username + ' memberikan anda donasi sejumlah Rp ' + jumlah_donasi
            notif_baru = Notifikasi.objects.create(penjual = toko_tujuan, isi = isi_notifikasi)
            notif_baru.save()
            return redirect('/donasi/terimakasih')
        else:
            donasierror = True
            context = {
                'formdonasi' : formDonasi,
                'users' : users,
                'usernow' : usernow,
                'donasierror' : donasierror
            }
            return render(request, 'donasi/index.html', context)

    context = {
        'formdonasi' : formDonasi,
        'users' : users,
        'usernow' : usernow,
        'donasierror' : donasi
    }

    return render(request, 'donasi/index.html', context)

def terimakasih(request):
    if (request.user.is_anonymous):
        return redirect('authuser:login')
    context = {}
    return render (request,'donasi/terimakasih.html')
    

def totaldonasi(request):
    total = 0
    allDonasi = Donasi.objects.all()
    userandtotal = {}
    for donasi in allDonasi:
        total += donasi.jumlahdonasi
        if (not donasi.pengirim in userandtotal):
            userandtotal[donasi.pengirim] = donasi.jumlahdonasi
        else :
            userandtotal[donasi.pengirim] += donasi.jumlahdonasi
    # print(userandtotal)
    sorteduserandtotal = sorted(userandtotal.items(), key=lambda userandtotal: userandtotal[1], reverse=True) 
    # print(sorteduserandtotal)
    context={
        'total' : total,
        'userandtotal' : sorteduserandtotal,
    }
    return render (request,'donasi/totaldonasi.html',context)

def donasi_api(request,nama):
    json_data = serializers.serialize('json', Donatur.objects.filter(namaDonatur__icontains=nama).order_by('jumlahDonasi','namaDonatur').reverse())    
    # print(json_data)
    return JsonResponse(json_data, safe=False)

def donasi_api2(request):
    # print(type(Donatur.objects.all()))
    json_data = serializers.serialize('json', Donatur.objects.order_by('jumlahDonasi','namaDonatur').reverse())  
    # print(json_data)
    return JsonResponse(json_data, safe=False)

donasi/templates/donasi/index.html
{% extends 'shared/base.html' %}

{% block title %}
Donasi
{% endblock title %}
{% block content %}
{% load static %}
<script src="{% static 'donasi/js/donasi.js' %}""></script>
<link rel="stylesheet" href="{% static 'donasi/css/style.css' %}">
<div class="container-fluid donasicontainer  ">
    <div class="container d-flex flex-column justify-content-center align-items-center">
        {% if donasierror %}
            <script>
                window.alert("Masukkan jumlah donasi yang sesuai")
            </script>
        {% endif %}
        <h1 class="mb-4">DONASI</h1>
        <p class="donasi mb-4"> Sederet dampak ditimbulkan wabah virus corona di berbagai sektor di Indonesia.
            Begitu juga sektor bisnis, bukan rahasia lagi, banyak dari perusahaan besar seperti hotel, restoran dan industri lain yang rugi bahkan gulung tikar akibat dari virus corona.
            Nasib serupa dialami oleh pelaku UKM, pedagang kecil dengan omset tak seberapa, yang dilakukan untuk menyambung hidup, kini kesulitan karena terdampak corona. Mari kita memberikan dukungan yang nyata bagi UMKM di Indonesia, mari berdonasi pada mereka yang membutuhkan agar tetap bisa berproduksi, memenuhi permintaan pelanggan, dan dengan demikian karyawan UMKM bisa hidup layak. Mari berbuat baik selagi masih ada kesempatan.</p>
            
            <form action="" method="POST">
                {% csrf_token %}
                <input name="pengirim" value="{{usernow}}" type="hidden">
                <div class="row">
                    <div class="col-lg-4">
                        <p class="donasi">Nama Toko Tujuan</p>
                    </div>
                    <div class="col-lg-6">
                        <select name="tokotujuan" required id="id_tokotujuan" placeholder="Pilih nama toko tujuan">
                            <option value="">Pilih nama toko tujuan</option>
                            {% for user in users %}
                                {% if user.username != usernow %}
                                <option value="{{user.id}}">{{user.username}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        
                        <!-- {{formdonasi.tokotujuan}} -->
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-4">
                        <p class="donasi">Jumlah Donasi</p>
                    </div>
                    <div class="col-lg-6">
                        {{ formdonasi.jumlahdonasi}}
                        <div class="donasihelp">
                            {{ formdonasi.jumlahdonasi.help_text}}

                        </div>
                        
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-lg-4">
                    </div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-warning float-right btndonatur" disabled> Donasi </button>
                    </div>
                </div>
            </form>
    </div>
</div>


{% endblock %}

donasi/templates/donasi/terimakasih.html
{% extends 'shared/base.html' %}

{% block title %}
Terima kasih
{% endblock title %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'donasi/css/style.css' %}">
<div class="container-fluid donasicontainer d-flex align-item-center">
    <div class="container d-flex flex-column justify-content-center align-items-center">
        <div>
            <h1 class="mb-2">Terima kasih telah berdonasi.</h1>
            <p class = "text-right mb-0">"No-one has become poor by giving"</p>
            <p class = "text-right">- Anne Frank </p>
        </div>
        <a class="btn btn-warning" href="{% url 'toko:index' %}" role="button">Kembali ke Halaman Depan</a>
    </div>
</div>

{% endblock %}

donasi/templates/donasi/totaldonasi.html
{% extends 'shared/base.html' %}

{% block title %}
Donasi
{% endblock title %}
{% block content %}
{% load static %}

<script src="{% static 'donasi/js/totaldonasi.js' %}"></script>
<link rel="stylesheet" href="{% static 'donasi/css/style.css' %}">
<div class="container-fluid donasicontainer d-flex flex-column justify-content-center align-items-center">
    <h1 class="mb-3 text-center">Total donasi yang telah disalurkan adalah</h1>
    <h2 class="mt-2">Rp{{total}},-</h2>
</div>
<div class="container-fluid total d-flex flex-column justify-content-center align-items-center px-4">
    <h1 class="mb-4 text-center">Terima kasih kepada para donatur</h1>
    <div class="active-pink-4 mb-4">
        <input class="form-control searchnama" type="text" placeholder="Search" aria-label="Search">
    </div>
    <button type="button" class="btn btn-warning mb-3 btndonatur">Cari berdasarkan nama donatur</button>
    <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nama Donatur</th>
            <th scope="col">Total Donasi</th>
          </tr>
        </thead>
        <tbody id="donatur">
        </tbody>
      </table>
</div>



{% endblock %}