authuser/urls.py
from django.urls import path, include

from .views import user_login, user_register, user_logout

urlpatterns = [
    path('login', user_login, name = 'login'),
    path('register', user_register, name = 'register'),
    path('logout', user_logout, name = 'logout')
]

app_name = 'authuser'

detail/urls.py
from django.urls import path

from .views import detailbarang,simpanUlasan

app_name = 'detail'

urlpatterns = [
    path('<int:id_barang>/', detailbarang, name = 'detail'),
    path('simpanUlasan/',simpanUlasan,name='simpanUlasan'),
]

setoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls', namespace = 'authuser')),
    path('', include('toko.urls', namespace = 'toko')),
    path('contactus/', include('contactus.urls', namespace = 'contactus')),
    path('donasi/', include('donasi.urls', namespace = 'donasi')),
    path('detail/', include('detail.urls', namespace = 'detail')),
    path('checkout/', include('checkout.urls', namespace = 'checkout')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path

from .views import index, toko, tambah, search_keyword, search_keyword_all, search_category, edit, hapus, toko_user, clean_notif, get_notif, cart, add_to_cart

urlpatterns = [
    path('toko/', toko, name = 'toko'),
    path('toko/tambah/', tambah, name = 'tambah'),
    path('toko/search/keyword/<str:keyword>/', search_keyword, name='search_keyword'),
    path('toko/search/keyword/', search_keyword_all, name='search_keyword_all'),
    path('toko/search/category/<str:category>/', search_category, name='search_category'),
    path('toko/edit/<int:id_barang>/', edit, name='edit'),
    path('toko/hapus/<int:id_barang>/', hapus, name='hapus'),
    path('toko/user/<int:id_user>/', toko_user, name='toko_user'),
    path('toko/user/cart/', cart, name='cart'),
    path('toko/api/notif/clean/', clean_notif, name='clean_notif'),
    path('toko/api/notif/get/', get_notif, name='get_notif'),
    path('toko/api/cart/add/', add_to_cart, name='add_to_cart'),
    path('', index, name = 'index'),
]

app_name = 'toko'

detail/models.py
from django.db import models
from toko.models import Barang
from django.conf import settings

# Create your models here.
class Ulasan(models.Model):
    ulasan = models.CharField(max_length = 150)
    id_barang = models.IntegerField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete = models.CASCADE
    )
    def __str__(self):
        return self.ulasan

detail/forms.py
from django import forms
from .models import Ulasan

class UlasanForm(forms.ModelForm):
    class Meta:
        model      = Ulasan
        fields     = [
            'ulasan',
            'id_barang',
            'user',
        ]
        widgets = {
            'ulasan': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan ulasan mengenai barang'
                }
            ),
        }

detail/views.py
from django.shortcuts import render
from toko.models import Barang, Notifikasi
from django.contrib.auth.models import User
from .models import Ulasan
from .forms import UlasanForm
from django.core import serializers
from django.http import HttpResponse
import json
# Create your views here.

def detailbarang(request,id_barang):
    barang = Barang.objects.get(id=id_barang)
    ulasan = Ulasan.objects.filter(id_barang=id_barang)
    ulasanForm = UlasanForm(request.POST or None)
    if (request.method == "POST"):
        ulasanForm = UlasanForm(request.POST)
        if (ulasanForm.is_valid()):
            ulasanForm.save()
    context = {
        'barang' : barang,
        'ulasanForm' : ulasanForm,
        'ulasan' : ulasan,
    }
    return render(request, 'detail/detailbarang.html', context)

def simpanUlasan(request):
    response={}
    nama_input = ""
    if (request.method =='POST'):
            nama_input = request.POST.get('user', False)
            id_barang_input = request.POST.get('id_barang_input', False)
            ulasan_input = request.POST.get('input_ulasan', False)
            print (id_barang_input)
            if ( ulasan_input != ""):
                Ulasan.objects.create(
                    user = request.user,
                    id_barang = id_barang_input,
                    ulasan = ulasan_input
                ).save() 
    response['message'] = nama_input
    return HttpResponse(json.dumps(response), content_type="application/json")

detail/templates/detail/detailbarang.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Pemersatu UMKM Indonesia
{% endblock title %}

{% block content %}
{% load static %}
{% load humanize %}

<style>
    p{
        font-size: 15px;
        margin-left: 30px;
    }

    .ammount-button:first-child {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }  

    .ammount-button{
        outline: none;
        cursor: pointer;
        font-size: .875rem;
        font-weight: 300;
        line-height: 1;
        letter-spacing: 0;
        display: flex;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        border: 1px solid rgba(0,0,0,.09);
        border-radius: 2px;
        background: transparent;
        color: rgba(0, 0, 0, 0.8);
        width: 32px;
        height: 32px;
        box-shadow: none;
    }

    div.input-quantity{
        display: flex;
    }

    .svg-icon{
        font-size: 10px;
        width: 10px;
        height: 10px;
        display: inline;
    }

    .ammount-input{
        -webkit-writing-mode: horizontal-tb !important;
        text-rendering: auto;
        word-spacing: normal;
        text-transform: none;
        text-indent: 0px;
        text-shadow: none;
        width: 50px;
        height: 32px;
        border-left: none;
        border-right: none;
        font-size: 16px;
        font-weight: 400;
        box-sizing: border-box;
        text-align: center;
        cursor: text;
        border-radius: 0;
    }

    .keranjang-button {
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        flex-direction: row;
        margin-right: 15px;
        min-width: 11.25rem;
        padding: 0 .75rem;
        font-size: 14px;
        color: #ee4d2d;
        background: rgba(255,87,34,.1);
        border: 1px solid #ee4d2d;
        box-shadow: 0 1px 1px 0 rgba(0,0,0,.03);
    }

    .keranjang-button span{
        color: #ee4d2d !important;
    }

    svg.cart-icon {
        color: #ee4d2d;
        stroke: #ee4d2d;
        fill: #ee4d2d;
        widht: 1em;
        height: 1em;
    }

    .overlay{
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      background: rgba(0,0, 0, 0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
    }

    .overlay-item{
      width: 50%;
      background-color: white;
      text-align: center;
      position: relative;
      padding-top: 3%;
      padding-bottom: 3%;
      border-radius: 8px;
    }

</style>
<link rel="stylesheet" href="{% static 'toko/css/style.css' %}">
<section id="Detail">
    <div class="container item-container" style="background-color: white; padding-top: 20px">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-12 item-container">
                <img src="{{barang.gambar.url}}" style="width: 90%">
            </div>
            <div class="col-md-6 col-sm-6 col-12 item-container">
                <h3>{{barang.nama}}</h3>
                <br>
                <h1 style="color: #ee4d2d">Rp{{barang.harga|intcomma}}</h1>
                <br>
                <h5>Deskripsi:</h5>
                <h6>{{barang.deskripsi}}</h6>
                <br>
                {% if barang.penjual.id != user.id %}
                <div class="_19lAw4 input-quantity">
                    <button class="ammount-button" onclick="clickDecButton(event)" style="padding:0">
                        <svg enable-background="new 0 0 10 10" viewBox="0 0 10 10" x="0" y="0" class="svg-icon ">
                            <polygon points="4.5 4.5 3.5 4.5 0 4.5 0 5.5 3.5 5.5 4.5 5.5 10 5.5 10 4.5">
                                
                            </polygon>
                        </svg>
                    </button>
                    <input type="number" min="1" class="ammount-button ammount-input _18Y8Ul" type="text" value="1">
                    <button class="ammount-button" onclick="clickPlusButton(event)">
                        <svg enable-background="new 0 0 10 10" viewBox="0 0 10 10" x="0" y="0" class="svg-icon icon-plus-sign">
                            <polygon points="10 4.5 5.5 4.5 5.5 0 4.5 0 4.5 4.5 0 4.5 0 5.5 4.5 5.5 4.5 10 5.5 10 5.5 5.5 10 5.5">
                                
                            </polygon>
                        </svg>
                    </button>
                </div>
                <br>
                <div class="action-container" style="display: flex">
                    <button type="button" class="keranjang-button" aria-disabled="false">
                        <svg enable-background="new 0 0 15 15" viewBox="0 0 15 15" x="0" y="0" class="cart-icon">
                            <g>
                                <g>
                                    <polyline fill="none" points=".5 .5 2.7 .5 5.2 11 12.4 11 14.5 3.5 3.7 3.5" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10">
                                        
                                    </polyline>
                                    <circle cx="6" cy="13.5" r="1" stroke="none" fill="#ee4d2d"></circle>
                                    <circle cx="11.5" cy="13.5" r="1" stroke="none" fill="#ee4d2d">
                                        
                                    </circle>
                                </g>
                                <line fill="none" stroke-linecap="round" stroke-miterlimit="10" x1="7.5" x2="10.5" y1="7" y2="7"></line>
                                <line fill="none" stroke-linecap="round" stroke-miterlimit="10" x1="9" x2="9" y1="8.5" y2="5.5">
                                    
                                </line>
                            </g>
                        </svg>
                        <span>Masukkan Keranjang</span>
                    </button>
                    <form action="{% url 'toko:cart' %}" method="POST">
                        {% csrf_token %}
                        <button>
                            <span>Beli Sekarang</span>
                        </button>
                        <input type = "number" name="id_barang" value="{{barang.id}}" hidden>
                        <input type = "number" name="user" value="{{user.id}}" hidden>
                        <input type = "text" name="gambar" value="{{barang.gambar}}" hidden>
                        <input type = "number" name="harga" value="{{barang.harga}}" hidden>
                        <input type="number" id="menu_1" name="menu_1" min="1" class="ammount-button ammount-input _18Y8Ul" type="text" value="1" hidden>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>

<section id="ulasan">
    <div class="container" id="ulasanBarang" style="background: white">
        <div class="ulasan_barang">
            <h3>Ulasan Produk</h3>
        {% for item in ulasan %}
            <p style='margin-bottom: 2px'>
                <b>{{item.user}}</b>
            </p>
            <p>
                {{item.ulasan}}
            </p>
        {% endfor %}
        </div>
        <br>
        {% if user.is_anonymous %}
            <p>Harap untuk melakukan <a href="{% url 'authuser:login' %}">login</a> agar dapat memberi komentar </p>
        {% else %}
            {% if barang.penjual.id != user.id %}
                <form id="ulasanForm">
                    {% csrf_token %}
                    <input for="idBarang" type = "select" name="id_barang" value="{{barang.id}}" hidden>
                    <input for="nama" type = "select" name="user" value="{{user.id}}" hidden>
                    <div class="form-group ">
                        <label for="ulasan "></label>
                        <textarea name="input_ulasan" id="pesan" class="form-control form-control-lg" maxlength="1000" form="usrform" style="height: 250px;" placeholder="Masukkan ulasan mengenai barang"></textarea>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary submitUlasan" style="background-color: #ee4d2d;">Kirim Ulasan</button>
                </form>
            {% endif %}
        {% endif %}
    </div>
</section>
<script>
    function clickPlusButton(event){
        event.preventDefault();
        event.target.parentNode.querySelector("input").stepUp();
        document.querySelector("#menu_1").stepUp();
    }

    function clickDecButton(event){
        event.preventDefault();
        event.target.parentNode.querySelector("input").stepDown();
        document.querySelector("#menu_1").stepDown();
    }


    $(".keranjang-button").click(function(){
        $.ajax({
            type: "POST",
            url: "{% url 'toko:add_to_cart' %}", 
            data: {
                id_barang: "{{ barang.id }}",
                jumlah: $('#menu_1').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function(){
                $("body").append(`
                <div class="overlay" onclick="turnoff()">
                    <div class="overlay-item">
                        <h1>Berhasil menambahkan ke keranjang!</h1>
                        <button id="overlay-close" onclick="turnoff()">OK</button>
                    </div>
                </div>
                `)
            }
        })
    })
    function turnoff(){
    $(".overlay").remove();
}

//ULASAN
    $(document).ready(function() {
        // form submit ajax
        $('.submitUlasan').click(function(e) {
            e.preventDefault();
            console.log($('#nama').val);
                $.ajax({
                    type: "POST",
                    url: "{% url 'detail:simpanUlasan' %}",
                    data: {
                        input_nama: $('#nama').val(),
                        id_barang_input :"{{barang.id}}",
                        input_ulasan: $('#pesan').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(response) {
                        const id = '{{user.username}}'
                        $('.ulasan_barang').append(
                            `
                            <p style='margin-bottom: 2px'>
                                <b>${id}</b>
                            </p>
                            <p>
                                ${$('#pesan').val()}
                            </p>
                            `
                        )
                        $("#pesan").val("")
                    },
                });
        });
    }); 


</script>


{% endblock content %}