checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout, name = 'checkout'),
    path('checkout/', views.cekot, name = 'cekot'),
    path('riwayat/', views.riwayat, name = 'riwayat'),
]

detail/urls.py
from django.urls import path

from .views import detailbarang,simpanUlasan

app_name = 'detail'

urlpatterns = [
    path('<int:id_barang>/', detailbarang, name = 'detail'),
    path('simpanUlasan/',simpanUlasan,name='simpanUlasan'),
]

setoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authuser.urls', namespace = 'authuser')),
    path('', include('toko.urls', namespace = 'toko')),
    path('contactus/', include('contactus.urls', namespace = 'contactus')),
    path('donasi/', include('donasi.urls', namespace = 'donasi')),
    path('detail/', include('detail.urls', namespace = 'detail')),
    path('checkout/', include('checkout.urls', namespace = 'checkout')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path

from .views import index, toko, tambah, search_keyword, search_keyword_all, search_category, edit, hapus, toko_user, clean_notif, get_notif, cart, add_to_cart

urlpatterns = [
    path('toko/', toko, name = 'toko'),
    path('toko/tambah/', tambah, name = 'tambah'),
    path('toko/search/keyword/<str:keyword>/', search_keyword, name='search_keyword'),
    path('toko/search/keyword/', search_keyword_all, name='search_keyword_all'),
    path('toko/search/category/<str:category>/', search_category, name='search_category'),
    path('toko/edit/<int:id_barang>/', edit, name='edit'),
    path('toko/hapus/<int:id_barang>/', hapus, name='hapus'),
    path('toko/user/<int:id_user>/', toko_user, name='toko_user'),
    path('toko/user/cart/', cart, name='cart'),
    path('toko/api/notif/clean/', clean_notif, name='clean_notif'),
    path('toko/api/notif/get/', get_notif, name='get_notif'),
    path('toko/api/cart/add/', add_to_cart, name='add_to_cart'),
    path('', index, name = 'index'),
]

app_name = 'toko'

toko/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Barang(models.Model):
    nama        = models.CharField(max_length = 300)
    deskripsi   = models.CharField(max_length = 1500)
    harga       = models.IntegerField()
    gambar      = models.ImageField(upload_to = 'images/')
    penjual     = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
    )
    kategori    = models.CharField(
        max_length = 100,
        choices = [
            ('Makanan', 'Makanan'),
            ('Minuman', 'Minuman'),
            ('Perabotan', 'Perabotan'),
            ('Mainan', 'Mainan'),
            ('Kerajinan', 'Kerajinan'),
            ('Alat Tulis', 'Alat Tulis'),
            ('Pakaian', 'Pakaian'),
            ('Handphone & Aksesoris', 'Handphone & Aksesoris'),
            ('Kesehatan', 'Kesehatan'),
            ('Pakaian Pria', 'Pakaian Pria'),
            ('Elektronik', 'Elektronik'),
            ('Hobi & Koleksi', 'Hobi & Koleksi'),
            ('Pakaian Wanita', 'Pakaian Wanita'),
            ('Tas Wanita', 'Tas Wanita'),
            ('Perawatan & Kecantikan', 'Perawatan & Kecantikan'),
            ('Perlengkapan Rumah', 'Perlengkapan Rumah'),
            ('Komputer & Aksesoris', 'Komputer & Aksesoris'),
            ('Buku & Alat Tulis', 'Buku & Alat Tulis'),
            ('Lain-Lain', 'Lain-Lain')
        ]    
    )

    def __str__(self):
        return '{}. {}'.format(self.id, self.nama)

class Notifikasi(models.Model):
    penjual = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
    )
    isi = models.CharField(max_length = 1000)
    tanggal = models.DateTimeField(auto_now_add = True)
    readed = models.BooleanField(default = False)
    
    class Meta:
        ordering = ['-tanggal']

class Cart(models.Model):
    penjual = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE
    )
    id_barang = models.IntegerField()
    jumlah_barang = models.IntegerField()

toko/forms.py
from django import forms
from .models import Barang

class BarangForm(forms.ModelForm):
    class Meta:
        model = Barang
        fields = [
            'nama',
            'deskripsi',
            'harga',
            'gambar',
            'penjual',
            'kategori'
        ]

        widgets = {
            'nama': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan Nama Barang'
                }
            ),
            'deskripsi': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan Deskripsi Barang'
                }
            ),
            'harga': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan Harga Barang'
                }
            ),
            'gambar': forms.FileInput(
                attrs = {
                    'class': 'form-control-file dropzone',
                }
            ),
            'kategori': forms.Select(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan Kategori Barang'
                }
            ),
        }

toko/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Barang, Notifikasi, Cart
from .forms import BarangForm
from django.contrib.auth.models import User 
from django.core import serializers
import json

# Landing Page
def index(request):

    items = Barang.objects.all()
    context = {
        'Items': items,
    }

    return render(request, 'toko/index.html', context)

# All Barang
def toko(request):
    items = Barang.objects.all()
    context = {
        'Items': items,
        'queryResult': 'semua barang'
    }

    return render(request, 'toko/toko.html', context)

# Search by category
def search_category(request, category):

    items = Barang.objects.all()
    items = [i for i in items if (category.lower() in i.kategori.lower())]
    context = {
        'Items': items,
        'queryResult': 'barang dengan kategori ' + category
    }

    return render(request, 'toko/toko.html', context)

# Search by keyword
def search_keyword(request, keyword):

    if (request.method == "POST" and request.POST['keyword'] == ''):
        return redirect('toko:search_keyword_all')

    if (request.method == "POST"):
        return redirect('toko:search_keyword', keyword = request.POST['keyword'])

    items = Barang.objects.all()
    items = [i for i in Barang.objects.all() if (keyword in "".join(i.nama.split()).lower())]
    context = {
        'Items': items,
        'queryResult': 'barang dengan kata kunci ' + keyword
    }

    return render(request, 'toko/toko.html', context)

def search_keyword_all(request):

    if (request.method == "POST"):
        return redirect('toko:search_keyword_all')

    items = Barang.objects.all()
    context = {
        'Items': items,
        'queryResult': 'Menampilkan semua barang '
    }

    return render(request, 'toko/toko.html', context)

# Tambah Barang
def tambah(request):

    if (request.user.is_anonymous):
        return redirect('authuser:login')

    form = BarangForm(request.POST or None)

    context = {
        'Heading': 'Tambah Barang',
        'Form': form,
        'imageurl': None,
        'successButtonText': 'Jual'
    }

    if (request.method == "POST"):
        form = BarangForm(request.POST, request.FILES)
        if (form.is_valid()):
            form.save()
        return redirect('toko:toko_user', id_user = request.user.id )

    return render(request, 'toko/Barangform.html', context)

# Edit Barang
def edit(request, id_barang):
    barang = ""
    try:
        barang = Barang.objects.get(id = id_barang)
    except:
        return redirect('toko:toko')
    if (request.method == "GET"):
        if (request.user.is_anonymous):
            return redirect('toko:toko')
        elif (request.user.id != barang.penjual.id):
            return redirect('toko:toko')
    
    if (request.method == "POST"):
        form = BarangForm(request.POST, request.FILES, instance = barang)
        if (form.is_valid()):
            form.save()
        return redirect('toko:toko_user', id_user = request.user.id )
    
    form = BarangForm(initial = {
        'nama': barang.nama,
        'deskripsi': barang.deskripsi,
        'harga': barang.harga,
        'gambar': barang.gambar,
        'penjual': barang.penjual,
        'kategory': barang.kategori
    }, instance = barang)

    context = {
        'Barang': barang,
        'Form': form,
        'Heading': 'Edit Barang ' + barang.nama,
        'imageurl': barang.gambar.url,
        'successButtonText': 'Simpan'
    }

    return render(request, 'toko/Barangform.html', context)

# Hapus Barang
def hapus(request, id_barang):

    if (request.user.is_anonymous):
        return redirect('authuser:login')

    barang = Barang.objects.get(id = id_barang)
    context = {
        'barang': barang
    }
    if (request.method == "POST"):
        barang.delete()
        return redirect('toko:toko_user', id_user = request.user.id)

    return render(request, 'toko/hapus_confirmation.html', context)

# Toko saya
def toko_user(request, id_user):
    items = Barang.objects.filter(penjual = User.objects.get(id = id_user))
    context = {
        'Items': items,
        'queryResult': 'barang dari penjual ' + User.objects.get(id = id_user).username
    }

    return render(request, 'toko/toko.html', context)

def cart(request):
    if (request.user.is_anonymous):
        return redirect('toko:toko')
    
    if (request.method == "POST"):
        cart = Cart.objects.create(penjual = request.user, id_barang = request.POST['id_barang'], jumlah_barang = request.POST['menu_1'])
        cart.save()
        return redirect('toko:cart')

    items = Cart.objects.filter(penjual = User.objects.get(id = request.user.id))
    items = [(Barang.objects.get(id = item.id_barang), item.jumlah_barang, item.id) for item in items]
    context = {
        'items': items
    }
    return render(request, 'toko/cart.html', context)

# Api Clean Notif
def clean_notif(request):
    allNotif = Notifikasi.objects.filter(penjual = request.user)
    for notif in allNotif:
        notif.readed = True
        notif.save()
    data = [{'success': True}]
    data = json.dumps(data)
    return HttpResponse(content = data, content_type="application/json")

# Api get notif
def get_notif(request):
    notif_json = serializers.serialize("json", Notifikasi.objects.filter(penjual = request.user))
    notif_json = json.dumps(notif_json)
    return HttpResponse(notif_json, content_type="application/json")

#Tambah barang
def add_to_cart(request):
    cart_baru = Cart( penjual=request.user, id_barang=int(request.POST.get("id_barang",False)), jumlah_barang=int(request.POST.get("jumlah",False)))
    cart_baru.save()
    data = [{'success': True}]
    data = json.dumps(data)
    return HttpResponse(content = data, content_type="application/json")

toko/templates/toko/Barangform.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Pemersatu UMKM Indonesia
{% endblock title %}

{% block content %}
{% load static %}
<style>
.box {
  position: relative;
  background: #ffffff;
  width: 100%;
}
.box-header {
  color: #444;
  display: block;
  padding: 10px;
  position: relative;
  border-bottom: 1px solid #f4f4f4;
  margin-bottom: 10px;
}
.box-tools {
  position: absolute;
  right: 10px;
  top: 5px;
}
.dropzone-wrapper {
  border: 2px dashed #91b0b3;
  color: #92b0b3;
  position: relative;
  height: 150px;
}
.dropzone-desc {
  position: absolute;
  margin: 0 auto;
  left: 0;
  right: 0;
  text-align: center;
  width: 40%;
  top: 50px;
  font-size: 16px;
}
.dropzone,
.dropzone:focus {
  position: absolute;
  outline: none !important;
  width: 100%;
  height: 150px;
  cursor: pointer;
  opacity: 0;
}
.dropzone-wrapper:hover,
.dropzone-wrapper.dragover {
  background: #ecf0f5;
}
</style>
<link rel="stylesheet" href="{% static 'toko/css/style.css' %}">
<section id="Edit">
    <div class="container">
        <h1 class="text-center">{{Heading}}</h1>
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}

            <div class="row">
                <div class="col-12 col-sm-12 col-md-4">
                    <div class="form-group">
                        {% if imageurl != None %}
                            <img src="{{imageurl}}" alt="{{Barang.nama}}" class="img-thumbnail">
                        {% endif %}
                        <div class="preview-zone hidden">
                            <div class="box box-solid">
                                <div class="box-header with-border">
                                    <div><b>Preview</b></div>
                                        <div class="box-tools pull-right">
                                        </div>
                                    </div>
                                <div class="box-body"></div>
                            </div>
                        </div>
                        
                        <label for="id_gambar">Gambar Barang</label>
                        <div class="dropzone-wrapper">
                            <div class="dropzone-desc">
                                <i class="glyphicon glyphicon-download-alt"></i>
                                <p>Choose an image file or drag it here.</p>
                            </div>
                            {{Form.gambar}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_harga">Harga Barang</label>
                        {{Form.harga}}
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-8">
                    <div class="form-group">
                        <label for="id_nama">Nama Barang</label>
                        {{Form.nama}}
                    </div>
                    <div class="form-group">
                        <label for="id_deskripsi">Deskripsi Barang</label>
                        {{Form.deskripsi}}
                    </div>
                    <div class="form-group">
                        <label for="id_kategori">Kategori Barang</label>
                        {{Form.kategori}}
                    </div>
                    <input type="select" name="penjual" value="{{user.id}}" hidden>
                    <button type="submit" class="btn btn-success btn-block">{{successButtonText}}</button>
                </div>
            </div>
        </form>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>
function readFile(input) {
 if (input.files && input.files[0]) {
 var reader = new FileReader();
 
 reader.onload = function (e) {
 var htmlPreview = 
 '<img width="200" src="' + e.target.result + '" />'+
 '<p>' + input.files[0].name + '</p>';
 var wrapperZone = $(input).parent();
 var previewZone = $(input).parent().parent().find('.preview-zone');
 var boxZone = $(input).parent().parent().find('.preview-zone').find('.box').find('.box-body');
 
 wrapperZone.removeClass('dragover');
 previewZone.removeClass('hidden');
 boxZone.empty();
 boxZone.append(htmlPreview);
 };
 
 reader.readAsDataURL(input.files[0]);
 }
}
function reset(e) {
 e.wrap('<form>').closest('form').get(0).reset();
 e.unwrap();
}
$(".dropzone").change(function(){
 readFile(this);
});
$('.dropzone-wrapper').on('dragover', function(e) {
 e.preventDefault();
 e.stopPropagation();
 $(this).addClass('dragover');
});
$('.dropzone-wrapper').on('dragleave', function(e) {
 e.preventDefault();
 e.stopPropagation();
 $(this).removeClass('dragover');
});
$('.remove-preview').on('click', function() {
 var boxZone = $(this).parents('.preview-zone').find('.box-body');
 var previewZone = $(this).parents('.preview-zone');
 var dropzone = $(this).parents('.form-group').find('.dropzone');
 boxZone.empty();
 previewZone.addClass('hidden');
 reset(dropzone);
});
</script>
{% endblock content %}

toko/templates/toko/hapus_confirmation.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Pemersatu UMKM Indonesia
{% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'toko/css/style.css' %}">
<section id="hapus">
    <div class="container">
        <h2 class="text-center">Apakah Anda Yakin Ingin Menghapus Barang {{barang.nama}}?</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 col-sm-12" style="display: flex; justify-content: center">
                    <button type="submit" class="btn btn-danger btn-block">Hapus</button>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

toko/templates/toko/index.html
{% extends 'shared/base.html' %}

{% block title %}
Setoko | Pemersatu UMKM Indonesia
{% endblock title %}

{% block content %}
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'toko/css/carousel.css' %}">
<link rel="stylesheet" href="{% static 'toko/css/style.css' %}">

<section id="kategory">
    <div class="container kategori-container">
        <div class="kategori-upper">
            <p>KATEGORI</p>
        </div>
        <div class="kategori-lower">
            <div class="row">
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Makanan' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Makanan.png' %}" alt="">
                        </div>
                        <p>Makanan</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Handphone & Aksesoris' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Handphone dan Aksesoris.png' %}" alt="">
                        </div>
                        <p>Handphone & Aksesoris</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Kesehatan' %}">  
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Kesehatan.png' %}" alt="">
                        </div>
                        <p>Kesehatan</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Pakaian Pria' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Pakaian Pria.png' %}" alt="">
                        </div>
                        <p>Pakaian Pria</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Elektronik' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Elektronik.png' %}" alt="">
                        </div>
                        <p>Elektronik</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Hobi & Koleksi' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Hobi dan Koleksi.png' %}" alt="">
                        </div>
                        <p>Hobi & Koleksi</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Pakaian Wanita' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Pakaian Wanita.png' %}" alt="">
                        </div>
                        <p>Pakaian Wanita</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Tas Wanita' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Tas Wanita.png' %}" alt="">
                        </div>
                        <p>Tas Wanita</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Perawatan & Kecantikan' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Perawatan dan Kecantikan.png' %}" alt="">
                        </div>
                        <p>Perawatan & Kecantikan</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Perlengkapan Rumah' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Perlengkapan Rumah.png' %}" alt="">
                        </div>
                        <p>Perlengkapan Rumah</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Komputer & Aksesoris' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Komputer dan Aksesoris.png' %}" alt="">
                        </div>
                        <p>Komputer & Aksesoris</p>
                    </a>
                </div>
                <div class="col-md-1 col-sm-2 col-2 category-box-container">
                    <a href="{% url 'toko:search_category' 'Buku & Alat Tulis' %}">
                        <div class="category-box">
                            <img class="kategori-img" src="{% static 'toko/img/icon/Buku dan Alat Tulis.png' %}" alt="">
                        </div>
                        <p>Buku & Alat Tulis</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="produk">
    <div class="container produk-container">
        <div class="row">
            {% for item in Items %}
                <div class="col-md-2 col-sm-6 col-6 d-flex align-item-stretch justify-content-center item-card-box" style="margin-bottom: 50px">
                    <div class="item-card">
                        <div class="item-data">
                            {% if user.is_authenticated %}
                                {% if item.penjual.id == user.id %}
                                    <div class="item-card-top" style="display: flex; justify-content: flex-end; padding: 5px">
                                        <a href="{% url 'toko:edit' item.id %}" data-toggle="tooltip" data-placement="top" title="Edit">
                                            <svg fill="#FF6F3C" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                        </a>
                                        <a href="{% url 'toko:hapus' item.id %}" data-toggle="tooltip" data-placement="top" title="Hapus">
                                            <svg fill="#FF6F3C" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="margin-left: 10px;">
                                                <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                            </svg>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endif %}
                            <div class="item-image">
                                <img src="{{item.gambar.url}}" alt="" style="width: 100%;">
                            </div>
                        </div>
                        <div class="item-card-info">
                            <p class="item-name">{{item.nama}}</p>
                            <p class="item-price">Rp{{item.harga|intcomma}}</p>
                        </div>
                        <a href="{% url 'detail:detail' item.id %}">
                            <div class="detail-box">
                                <p>Lihat Detail</p>
                            </div>
                        </a>
                    </div>
                </div>  
            {% endfor %}
        </div>
    </div>
</section>


{% endblock content %}